### PR TITLE
Jay

### PR DESCRIPTION
**Pull request by dujay971226**
For TUT

### CODE REVIEW

**Comment by XFF227** [comment]
good program! keep completing the use case code. some problem in communicate with the PubNub api should be solved.

**Comment by huang-zhi-hao** [comment]
Great work. Many of the important api portion of the project were successfully implemented. Fix errors relating to the chat function using the PubNub api.

**Comment by JunkeHou** [comment]
It's fantastic! But some usecases need to be included.

**Comment by GriRet** [comment]
It would be great if the ordering of the architecture could be managed to improve in the aspect of correct location of the code

**Pull request closed without merging**
