### PR TITLE
Xiaofeng

### PR DESCRIPTION
**Pull request by XFF227**
Added code for the profile view section, and entity initialization for user and channel

### CODE REVIEW

**Comment by GriRet** [comment]
great progress! your ideas about the ways to transit data across different use cases really inspired me for writing a reasonable code. Also your code structure following the CA engine deliberately provides a solid bases for us since majority of codes would need to take data and responses from your modules.

**Comment by dujay971226** [comment]
Descent progress, keep working on use-case and view. If possible work on the channel entity and user entity.
The collaboration of my Room and your Profile will be discussed during the meeting later

**Comment by huang-zhi-hao** [comment]
Great progress! We need to fix any errors and merge our codes together in order to transition from your view to mine.

**Comment by JunkeHou** [comment]
It's done quite well! One of the usecases is split into two to make it simpler and easier to write in order to achieve clean architecture.

**Pull request closed without merging**
