### PR TITLE
houjunke

### PR DESCRIPTION
**Pull request by JunkeHou**
Adding sign up and login.

### CODE REVIEW

**Comment by GriRet** [comment]
It looks like a large portion of code where changed due to the change in the idea of the implementation, but overall speaking, the code after change appeals more coherent to the CA engine and overall structure

**Comment by dujay971226** [comment]
Good Progress, lacking use-case and creating a user on pubhub. Fix what we discussed and we will work on the collab between you and xiaofeng in the meeting

**Comment by huang-zhi-hao** [comment]
Great structure which follows the clean architecture design principles. I noticed that there is the need to add missing PubNub  instance as it will be passed to other rooms through their state classes.

**Comment by XFF227** [comment]
Good job! you could go further to implement the signup presenter. We can discuss the detail of work between our program later.

**Pull request closed without merging**
