### PR TITLE
Harvey

### PR DESCRIPTION
**Pull request by huang-zhi-hao**
Create room and subscribe room

### CODE REVIEW

**Comment by dujay971226** [comment]
Create and subscribe need to add subscribe to pubnub. Otherwise, great progress, keep working, and hopefully, complete everything but UI next Mon.

**Comment by XFF227** [comment]
good job! a PubNub and user attribute should be added into each state. Some data access object should be use to get the recent channel when subscribe channel.

**Comment by JunkeHou** [comment]
This is a difficult portion, and you did an excellent job! However, in your part, you must still include the use of user and pubnub in the create and subscribe states.

**Comment by GriRet** [comment]
Well down! I only have a little bit question about the part of the code that stores a copy of the room and channel data offline. It seems like you should include these codes to form complete use cases.

**Pull request closed without merging**
