### PR TITLE
Change in Channel Setting

### PR DESCRIPTION
**Pull request by GriRet**
Add a bunch of framework of Channel Setting usecases and interactor adapters and view models
Zheyu Zheng

### CODE REVIEW

**Comment by GriRet** [comment]
After having a communication with jay who develops the Room part of the Chat App, I feels like several use cases are infeasible to achieve within reasonable time and framework and several other use cases requires change in implementation. But the code structure and functionality becomes clearer after discussion and I'm more confident to write delegent and CA engine compatible code.

**Comment by JunkeHou** [comment]
Your code is really well written overall, but there are a few elements lacking in the channel setting. Setting up message reception in the channel, for example, and implementing the option to remove people from the channel's chat group.

**Comment by dujay971226** [comment]
Good implementation, however, features such as chang color as we discussed might not be implementable. Revise that and keep working.

**Comment by XFF227** [comment]
your idea is excellent, you can keep completing each use case and connect your program with Jay's.

**Comment by huang-zhi-hao** [comment]
Awesome progress. I noticed many empty classes that you need to consider and complete.

**Pull request closed without merging**
